name: Build and Release JAR
on:
  push:
    tags:
      - "v*"
permissions:
  contents: write
jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: "8"
          distribution: "zulu"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build with Gradle wrapper
        run: |
          OUTPUT=$(./gradlew -q releaseJar --no-configuration-cache)
          JAR_PATH=$(echo "$OUTPUT" | sed -n '1p')
          SOURCES_PATH=$(echo "$OUTPUT" | sed -n '2p')
          echo "JAR_PATH=$JAR_PATH" >> "$GITHUB_ENV"
          echo "SOURCES_PATH=$SOURCES_PATH" >> "$GITHUB_ENV"
      - name: Release
        uses: softprops/action-gh-release@v2.2.1
        with:
          files: |
            ${{ env.JAR_PATH }}
            ${{ env.SOURCES_PATH }}
